# Generated by Django 3.0.7 on 2020-09-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticipo',
            options={'ordering': ['id'], 'verbose_name': 'Anticipo', 'verbose_name_plural': 'Anticipos'},
        ),
    ]
