# Generated by Django 3.0.7 on 2020-10-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0002_auto_20201023_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='comprobantes_Cancelados',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='monto_comprobantes',
        ),
        migrations.AddField(
            model_name='recibo',
            name='comprobantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Comprobante', verbose_name='Comprobantes Cancelados'),
        ),
    ]
