# Generated by Django 3.0.7 on 2020-09-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0002_auto_20200924_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='comprobantegenerado',
            options={'ordering': ['id']},
        ),
    ]
