# Generated by Django 3.0.7 on 2020-09-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0003_remove_cheque_cheque_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque_recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Recibo', verbose_name='Recibo'),
        ),
    ]
