# Generated by Django 3.0.7 on 2020-09-25 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SGCapp', '0003_auto_20200924_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='user_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_caja', to=settings.AUTH_USER_MODEL, verbose_name='usuario caja'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto Original'),
        ),
        migrations.AlterField(
            model_name='comprobantegenerado',
            name='comprobante_recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Recibo', verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='recibo_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Caja', verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='recibo_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Planilla', verbose_name='Planilla'),
        ),
    ]
