# Generated by Django 3.0.7 on 2020-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0004_cheque_cheque_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_recibo',
        ),
    ]
