# Generated by Django 3.0.7 on 2020-09-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0004_auto_20200924_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='comprobante_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SGCapp.Cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
