# Generated by Django 3.0.7 on 2020-09-18 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='user_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_caja', to=settings.AUTH_USER_MODEL, verbose_name='usuario caja'),
        ),
    ]
