# Generated by Django 3.0.7 on 2020-09-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGCapp', '0007_auto_20200918_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
